<?php

namespace Database\Seeders;

use App\Models\Icon;
use Illuminate\Database\Seeder;

class IconSeeder extends Seeder
{
    public function run(): void
    {
        $icons = [
            // ---- Dashboard & General ----
            ['code' => 'fa-solid fa-house',              'name' => 'House'],
            ['code' => 'fa-solid fa-gauge-high',         'name' => 'Dashboard'],
            ['code' => 'fa-solid fa-chart-line',         'name' => 'Chart Line'],
            ['code' => 'fa-solid fa-chart-pie',          'name' => 'Chart Pie'],
            ['code' => 'fa-solid fa-chart-bar',          'name' => 'Chart Bar'],
            ['code' => 'fa-solid fa-chart-area',         'name' => 'Chart Area'],
            ['code' => 'fa-solid fa-arrow-trend-up',    'name' => 'Trend Up'],
            ['code' => 'fa-solid fa-arrow-trend-down',  'name' => 'Trend Down'],
            ['code' => 'fa-solid fa-ranking-star',      'name' => 'Ranking'],
            ['code' => 'fa-solid fa-chart-simple',      'name' => 'Chart Simple'],

            // ---- Users & People ----
            ['code' => 'fa-solid fa-user',              'name' => 'User'],
            ['code' => 'fa-solid fa-users',             'name' => 'Users'],
            ['code' => 'fa-solid fa-user-group',        'name' => 'User Group'],
            ['code' => 'fa-solid fa-user-tie',          'name' => 'User Tie'],
            ['code' => 'fa-solid fa-user-shield',       'name' => 'User Shield'],
            ['code' => 'fa-solid fa-user-gear',         'name' => 'User Gear'],
            ['code' => 'fa-solid fa-user-pen',          'name' => 'User Pen'],
            ['code' => 'fa-solid fa-user-check',        'name' => 'User Check'],
            ['code' => 'fa-solid fa-user-clock',        'name' => 'User Clock'],
            ['code' => 'fa-solid fa-user-plus',         'name' => 'User Plus'],
            ['code' => 'fa-solid fa-user-minus',        'name' => 'User Minus'],
            ['code' => 'fa-solid fa-people-group',      'name' => 'People Group'],
            ['code' => 'fa-solid fa-people-arrows',     'name' => 'People Arrows'],
            ['code' => 'fa-solid fa-people-line',       'name' => 'People Line'],

            // ---- Security & Access ----
            ['code' => 'fa-solid fa-lock',              'name' => 'Lock'],
            ['code' => 'fa-solid fa-lock-open',         'name' => 'Lock Open'],
            ['code' => 'fa-solid fa-key',               'name' => 'Key'],
            ['code' => 'fa-solid fa-shield-halved',     'name' => 'Shield'],
            ['code' => 'fa-solid fa-shield',            'name' => 'Shield Solid'],
            ['code' => 'fa-solid fa-fingerprint',       'name' => 'Fingerprint'],
            ['code' => 'fa-solid fa-user-lock',         'name' => 'User Lock'],
            ['code' => 'fa-solid fa-eye',               'name' => 'Eye'],
            ['code' => 'fa-solid fa-eye-slash',         'name' => 'Eye Slash'],

            // ---- Files & Documents ----
            ['code' => 'fa-solid fa-file',              'name' => 'File'],
            ['code' => 'fa-solid fa-file-lines',        'name' => 'File Lines'],
            ['code' => 'fa-solid fa-file-image',        'name' => 'File Image'],
            ['code' => 'fa-solid fa-file-pdf',          'name' => 'File PDF'],
            ['code' => 'fa-solid fa-file-word',         'name' => 'File Word'],
            ['code' => 'fa-solid fa-file-excel',        'name' => 'File Excel'],
            ['code' => 'fa-solid fa-file-powerpoint',   'name' => 'File PowerPoint'],
            ['code' => 'fa-solid fa-file-zipper',       'name' => 'File Zipper'],
            ['code' => 'fa-solid fa-file-code',         'name' => 'File Code'],
            ['code' => 'fa-solid fa-file-csv',          'name' => 'File CSV'],
            ['code' => 'fa-solid fa-folder',            'name' => 'Folder'],
            ['code' => 'fa-solid fa-folder-open',       'name' => 'Folder Open'],
            ['code' => 'fa-solid fa-folder-tree',       'name' => 'Folder Tree'],
            ['code' => 'fa-solid fa-copy',              'name' => 'Copy'],
            ['code' => 'fa-solid fa-clone',             'name' => 'Clone'],
            ['code' => 'fa-solid fa-download',          'name' => 'Download'],
            ['code' => 'fa-solid fa-upload',            'name' => 'Upload'],
            ['code' => 'fa-solid fa-cloud-arrow-up',    'name' => 'Cloud Upload'],
            ['code' => 'fa-solid fa-cloud-arrow-down',  'name' => 'Cloud Download'],

            // ---- Commerce & Shopping ----
            ['code' => 'fa-solid fa-cart-shopping',     'name' => 'Cart Shopping'],
            ['code' => 'fa-solid fa-bag-shopping',      'name' => 'Bag Shopping'],
            ['code' => 'fa-solid fa-store',             'name' => 'Store'],
            ['code' => 'fa-solid fa-shop',              'name' => 'Shop'],
            ['code' => 'fa-solid fa-shop-slash',        'name' => 'Shop Slash'],
            ['code' => 'fa-solid fa-tag',               'name' => 'Tag'],
            ['code' => 'fa-solid fa-tags',              'name' => 'Tags'],
            ['code' => 'fa-solid fa-barcode',           'name' => 'Barcode'],
            ['code' => 'fa-solid fa-money-bill',        'name' => 'Money Bill'],
            ['code' => 'fa-solid fa-money-bill-wave',   'name' => 'Money Bill Wave'],
            ['code' => 'fa-solid fa-coins',             'name' => 'Coins'],
            ['code' => 'fa-solid fa-wallet',            'name' => 'Wallet'],
            ['code' => 'fa-solid fa-credit-card',       'name' => 'Credit Card'],
            ['code' => 'fa-solid fa-receipt',           'name' => 'Receipt'],
            ['code' => 'fa-solid fa-file-invoice-dollar', 'name' => 'Invoice Dollar'],
            ['code' => 'fa-solid fa-scale-balanced',    'name' => 'Scale Balanced'],
            ['code' => 'fa-solid fa-hand-holding-dollar', 'name' => 'Hand Holding Dollar'],
            ['code' => 'fa-solid fa-piggy-bank',        'name' => 'Piggy Bank'],

            // ---- Communication ----
            ['code' => 'fa-solid fa-envelope',          'name' => 'Envelope'],
            ['code' => 'fa-solid fa-envelope-open',     'name' => 'Envelope Open'],
            ['code' => 'fa-solid fa-inbox',             'name' => 'Inbox'],
            ['code' => 'fa-solid fa-paper-plane',       'name' => 'Paper Plane'],
            ['code' => 'fa-solid fa-comment',           'name' => 'Comment'],
            ['code' => 'fa-solid fa-comments',          'name' => 'Comments'],
            ['code' => 'fa-solid fa-comment-dots',      'name' => 'Comment Dots'],
            ['code' => 'fa-solid fa-message',           'name' => 'Message'],
            ['code' => 'fa-solid fa-messages',          'name' => 'Messages'],
            ['code' => 'fa-solid fa-phone',             'name' => 'Phone'],
            ['code' => 'fa-solid fa-phone-volume',      'name' => 'Phone Volume'],
            ['code' => 'fa-solid fa-phone-slash',       'name' => 'Phone Slash'],
            ['code' => 'fa-solid fa-video',             'name' => 'Video'],
            ['code' => 'fa-solid fa-video-slash',       'name' => 'Video Slash'],
            ['code' => 'fa-solid fa-microphone',        'name' => 'Microphone'],
            ['code' => 'fa-solid fa-microphone-slash',  'name' => 'Microphone Slash'],
            ['code' => 'fa-solid fa-headset',           'name' => 'Headset'],

            // ---- Website & Internet ----
            ['code' => 'fa-solid fa-globe',             'name' => 'Globe'],
            ['code' => 'fa-solid fa-globe-americas',    'name' => 'Globe Americas'],
            ['code' => 'fa-solid fa-link',              'name' => 'Link'],
            ['code' => 'fa-solid fa-link-slash',        'name' => 'Link Slash'],
            ['code' => 'fa-solid fa-chain',             'name' => 'Chain'],
            ['code' => 'fa-solid fa-share',             'name' => 'Share'],
            ['code' => 'fa-solid fa-share-nodes',       'name' => 'Share Nodes'],
            ['code' => 'fa-solid fa-qrcode',            'name' => 'QR Code'],
            ['code' => 'fa-solid fa-wifi',              'name' => 'WiFi'],
            ['code' => 'fa-solid fa-signal',            'name' => 'Signal'],
            ['code' => 'fa-solid fa-satellite-dish',    'name' => 'Satellite Dish'],
            ['code' => 'fa-solid fa-earth-americas',    'name' => 'Earth Americas'],
            ['code' => 'fa-solid fa-magnifying-glass',  'name' => 'Search'],

            // ---- Media & Design ----
            ['code' => 'fa-solid fa-image',             'name' => 'Image'],
            ['code' => 'fa-solid fa-images',            'name' => 'Images'],
            ['code' => 'fa-solid fa-photo-film',        'name' => 'Photo Film'],
            ['code' => 'fa-solid fa-palette',           'name' => 'Palette'],
            ['code' => 'fa-solid fa-paintbrush',        'name' => 'Paintbrush'],
            ['code' => 'fa-solid fa-pen',               'name' => 'Pen'],
            ['code' => 'fa-solid fa-pen-nib',           'name' => 'Pen Nib'],
            ['code' => 'fa-solid fa-pen-to-square',     'name' => 'Pen To Square'],
            ['code' => 'fa-solid fa-wand-magic-sparkles', 'name' => 'Magic Wand'],
            ['code' => 'fa-solid fa-paint-roller',      'name' => 'Paint Roller'],
            ['code' => 'fa-solid fa-sliders',           'name' => 'Sliders'],
            ['code' => 'fa-solid fa-sliders-h',         'name' => 'Sliders H'],
            ['code' => 'fa-solid fa-puzzle-piece',      'name' => 'Puzzle Piece'],
            ['code' => 'fa-solid fa-shapes',            'name' => 'Shapes'],
            ['code' => 'fa-solid fa-draw-polygon',      'name' => 'Draw Polygon'],
            ['code' => 'fa-solid fa-vector-square',     'name' => 'Vector Square'],

            // ---- Layout & UI ----
            ['code' => 'fa-solid fa-table-cells',       'name' => 'Table Cells'],
            ['code' => 'fa-solid fa-table-cells-large', 'name' => 'Table Cells Large'],
            ['code' => 'fa-solid fa-table-list',        'name' => 'Table List'],
            ['code' => 'fa-solid fa-table-columns',     'name' => 'Table Columns'],
            ['code' => 'fa-solid fa-table-rows',        'name' => 'Table Rows'],
            ['code' => 'fa-solid fa-border-all',        'name' => 'Border All'],
            ['code' => 'fa-solid fa-border-none',       'name' => 'Border None'],
            ['code' => 'fa-solid fa-border-top-left',   'name' => 'Border Top Left'],
            ['code' => 'fa-solid fa-columns',           'name' => 'Columns'],
            ['code' => 'fa-solid fa-rows',              'name' => 'Rows'],
            ['code' => 'fa-solid fa-grid',              'name' => 'Grid'],
            ['code' => 'fa-solid fa-layer-group',       'name' => 'Layer Group'],
            ['code' => 'fa-solid fa-layer-group',       'name' => 'Stack Layers'],
            ['code' => 'fa-solid fa-object-group',      'name' => 'Object Group'],
            ['code' => 'fa-solid fa-object-ungroup',    'name' => 'Object Ungroup'],
            ['code' => 'fa-solid fa-sidebar',           'name' => 'Sidebar'],
            ['code' => 'fa-solid fa-sidebar-flip',      'name' => 'Sidebar Flip'],

            // ---- Content & Pages ----
            ['code' => 'fa-solid fa-file-lines',       'name' => 'File Lines'],
            ['code' => 'fa-solid fa-newspaper',         'name' => 'Newspaper'],
            ['code' => 'fa-solid fa-book',              'name' => 'Book'],
            ['code' => 'fa-solid fa-book-open',         'name' => 'Book Open'],
            ['code' => 'fa-solid fa-bookmark',          'name' => 'Bookmark'],
            ['code' => 'fa-solid fa-bookmarks',         'name' => 'Bookmarks'],
            ['code' => 'fa-solid fa-scroll',            'name' => 'Scroll'],
            ['code' => 'fa-solid fa-list',              'name' => 'List'],
            ['code' => 'fa-solid fa-list-check',        'name' => 'List Check'],
            ['code' => 'fa-solid fa-list-ul',           'name' => 'List UL'],
            ['code' => 'fa-solid fa-list-ol',           'name' => 'List OL'],
            ['code' => 'fa-solid fa-table',             'name' => 'Table'],

            // ---- System & Tools ----
            ['code' => 'fa-solid fa-gear',              'name' => 'Gear'],
            ['code' => 'fa-solid fa-gears',             'name' => 'Gears'],
            ['code' => 'fa-solid fa-wrench',            'name' => 'Wrench'],
            ['code' => 'fa-solid fa-screwdriver-wrench', 'name' => 'Screwdriver Wrench'],
            ['code' => 'fa-solid fa-hammer',            'name' => 'Hammer'],
            ['code' => 'fa-solid fa-screwdriver',       'name' => 'Screwdriver'],
            ['code' => 'fa-solid fa-toolbox',           'name' => 'Toolbox'],
            ['code' => 'fa-solid fa-sliders',           'name' => 'Controls'],
            ['code' => 'fa-solid fa-toggle-on',         'name' => 'Toggle On'],
            ['code' => 'fa-solid fa-toggle-off',        'name' => 'Toggle Off'],
            ['code' => 'fa-solid fa-sliders',           'name' => 'Sliders'],
            ['code' => 'fa-solid fa-rotate',            'name' => 'Rotate'],
            ['code' => 'fa-solid fa-arrows-rotate',     'name' => 'Arrows Rotate'],
            ['code' => 'fa-solid fa-sync',              'name' => 'Sync'],
            ['code' => 'fa-solid fa-sync-alt',          'name' => 'Sync Alt'],
            ['code' => 'fa-solid fa-rotate-left',       'name' => 'Rotate Left'],
            ['code' => 'fa-solid fa-rotate-right',      'name' => 'Rotate Right'],

            // ---- Status & Actions ----
            ['code' => 'fa-solid fa-check',             'name' => 'Check'],
            ['code' => 'fa-solid fa-check-double',      'name' => 'Check Double'],
            ['code' => 'fa-solid fa-circle-check',      'name' => 'Circle Check'],
            ['code' => 'fa-solid fa-xmark',             'name' => 'Xmark'],
            ['code' => 'fa-solid fa-circle-xmark',      'name' => 'Circle Xmark'],
            ['code' => 'fa-solid fa-exclamation',       'name' => 'Exclamation'],
            ['code' => 'fa-solid fa-circle-exclamation', 'name' => 'Circle Exclamation'],
            ['code' => 'fa-solid fa-triangle-exclamation', 'name' => 'Triangle Exclamation'],
            ['code' => 'fa-solid fa-circle-info',       'name' => 'Circle Info'],
            ['code' => 'fa-solid fa-question',          'name' => 'Question'],
            ['code' => 'fa-solid fa-circle-question',   'name' => 'Circle Question'],

            // ---- Arrows & Navigation ----
            ['code' => 'fa-solid fa-plus',              'name' => 'Plus'],
            ['code' => 'fa-solid fa-plus-circle',       'name' => 'Plus Circle'],
            ['code' => 'fa-solid fa-minus',             'name' => 'Minus'],
            ['code' => 'fa-solid fa-minus-circle',      'name' => 'Minus Circle'],
            ['code' => 'fa-solid fa-trash',             'name' => 'Trash'],
            ['code' => 'fa-solid fa-trash-can',         'name' => 'Trash Can'],
            ['code' => 'fa-solid fa-pen-to-square',     'name' => 'Edit'],
            ['code' => 'fa-solid fa-circle-plus',       'name' => 'Circle Plus'],
            ['code' => 'fa-solid fa-circle-minus',      'name' => 'Circle Minus'],
            ['code' => 'fa-solid fa-circle-info',       'name' => 'Info'],
            ['code' => 'fa-solid fa-arrow-right',       'name' => 'Arrow Right'],
            ['code' => 'fa-solid fa-arrow-left',        'name' => 'Arrow Left'],
            ['code' => 'fa-solid fa-arrow-up',          'name' => 'Arrow Up'],
            ['code' => 'fa-solid fa-arrow-down',        'name' => 'Arrow Down'],
            ['code' => 'fa-solid fa-arrows-up-down',    'name' => 'Arrows Up Down'],
            ['code' => 'fa-solid fa-arrows-left-right', 'name' => 'Arrows Left Right'],
            ['code' => 'fa-solid fa-angles-right',      'name' => 'Angles Right'],
            ['code' => 'fa-solid fa-angles-left',       'name' => 'Angles Left'],
            ['code' => 'fa-solid fa-angle-right',       'name' => 'Angle Right'],
            ['code' => 'fa-solid fa-angle-left',        'name' => 'Angle Left'],
            ['code' => 'fa-solid fa-angle-down',        'name' => 'Angle Down'],
            ['code' => 'fa-solid fa-angle-up',          'name' => 'Angle Up'],
            ['code' => 'fa-solid fa-chevron-right',     'name' => 'Chevron Right'],
            ['code' => 'fa-solid fa-chevron-left',      'name' => 'Chevron Left'],
            ['code' => 'fa-solid fa-chevron-down',      'name' => 'Chevron Down'],
            ['code' => 'fa-solid fa-chevron-up',        'name' => 'Chevron Up'],

            // ---- Calendar & Time ----
            ['code' => 'fa-solid fa-calendar',          'name' => 'Calendar'],
            ['code' => 'fa-solid fa-calendar-days',     'name' => 'Calendar Days'],
            ['code' => 'fa-solid fa-calendar-check',    'name' => 'Calendar Check'],
            ['code' => 'fa-solid fa-calendar-plus',     'name' => 'Calendar Plus'],
            ['code' => 'fa-solid fa-calendar-minus',    'name' => 'Calendar Minus'],
            ['code' => 'fa-solid fa-clock',             'name' => 'Clock'],
            ['code' => 'fa-solid fa-clock-rotate-left', 'name' => 'Clock Rotate Left'],
            ['code' => 'fa-solid fa-hourglass',         'name' => 'Hourglass'],
            ['code' => 'fa-solid fa-hourglass-half',    'name' => 'Hourglass Half'],
            ['code' => 'fa-solid fa-stopwatch',         'name' => 'Stopwatch'],
            ['code' => 'fa-solid fa-timer',             'name' => 'Timer'],

            // ---- Maps & Location ----
            ['code' => 'fa-solid fa-location-dot',      'name' => 'Location Dot'],
            ['code' => 'fa-solid fa-location-dot',      'name' => 'Map Marker'],
            ['code' => 'fa-solid fa-map',               'name' => 'Map'],
            ['code' => 'fa-solid fa-map-location-dot',  'name' => 'Map Location Dot'],
            ['code' => 'fa-solid fa-map-pin',           'name' => 'Map Pin'],
            ['code' => 'fa-solid fa-route',             'name' => 'Route'],
            ['code' => 'fa-solid fa-road',              'name' => 'Road'],

            // ---- Notification & Alerts ----
            ['code' => 'fa-solid fa-bell',              'name' => 'Bell'],
            ['code' => 'fa-solid fa-bell-concierge',    'name' => 'Bell Concierge'],
            ['code' => 'fa-solid fa-bell-slash',        'name' => 'Bell Slash'],
            ['code' => 'fa-solid fa-bells',             'name' => 'Bells'],
            ['code' => 'fa-solid fa-trophy',            'name' => 'Trophy'],
            ['code' => 'fa-solid fa-medal',             'name' => 'Medal'],
            ['code' => 'fa-solid fa-award',             'name' => 'Award'],

            // ---- Food & Beverage ----
            ['code' => 'fa-solid fa-utensils',          'name' => 'Utensils'],
            ['code' => 'fa-solid fa-utensils-slash',    'name' => 'Utensils Slash'],
            ['code' => 'fa-solid fa-mug-hot',           'name' => 'Mug Hot'],
            ['code' => 'fa-solid fa-wine-glass',        'name' => 'Wine Glass'],
            ['code' => 'fa-solid fa-beer-mug-empty',    'name' => 'Beer Mug'],

            // ---- Transport ----
            ['code' => 'fa-solid fa-car',               'name' => 'Car'],
            ['code' => 'fa-solid fa-car-side',          'name' => 'Car Side'],
            ['code' => 'fa-solid fa-truck',             'name' => 'Truck'],
            ['code' => 'fa-solid fa-truck-fast',        'name' => 'Truck Fast'],
            ['code' => 'fa-solid fa-truck-moving',      'name' => 'Truck Moving'],
            ['code' => 'fa-solid fa-plane',             'name' => 'Plane'],
            ['code' => 'fa-solid fa-plane-departure',   'name' => 'Plane Departure'],
            ['code' => 'fa-solid fa-plane-arrival',     'name' => 'Plane Arrival'],
            ['code' => 'fa-solid fa-ship',              'name' => 'Ship'],

            // ---- Device & Tech ----
            ['code' => 'fa-solid fa-computer',          'name' => 'Computer'],
            ['code' => 'fa-solid fa-laptop',            'name' => 'Laptop'],
            ['code' => 'fa-solid fa-desktop',           'name' => 'Desktop'],
            ['code' => 'fa-solid fa-tablet',            'name' => 'Tablet'],
            ['code' => 'fa-solid fa-mobile',            'name' => 'Mobile'],
            ['code' => 'fa-solid fa-mobile-screen',     'name' => 'Mobile Screen'],
            ['code' => 'fa-solid fa-tv',                'name' => 'TV'],
            ['code' => 'fa-solid fa-print',             'name' => 'Print'],
            ['code' => 'fa-solid fa-keyboard',          'name' => 'Keyboard'],
            ['code' => 'fa-solid fa-hard-drive',        'name' => 'Hard Drive'],
            ['code' => 'fa-solid fa-server',            'name' => 'Server'],
            ['code' => 'fa-solid fa-database',          'name' => 'Database'],
            ['code' => 'fa-solid fa-memory',            'name' => 'Memory'],
            ['code' => 'fa-solid fa-microchip',         'name' => 'Microchip'],
            ['code' => 'fa-solid fa-usb',               'name' => 'USB'],

            // ---- Code & Development ----
            ['code' => 'fa-solid fa-code',              'name' => 'Code'],
            ['code' => 'fa-solid fa-code-branch',       'name' => 'Code Branch'],
            ['code' => 'fa-solid fa-code-pull-request', 'name' => 'Code Pull Request'],
            ['code' => 'fa-solid fa-terminal',          'name' => 'Terminal'],
            ['code' => 'fa-solid fa-console',           'name' => 'Console'],
            ['code' => 'fa-solid fa-bug',               'name' => 'Bug'],
            ['code' => 'fa-solid fa-bug-slash',         'name' => 'Bug Slash'],
            ['code' => 'fa-solid fa-robot',             'name' => 'Robot'],
            ['code' => 'fa-solid fa-cube',              'name' => 'Cube'],
            ['code' => 'fa-solid fa-cubes',             'name' => 'Cubes'],

            // ---- Education ----
            ['code' => 'fa-solid fa-graduation-cap',    'name' => 'Graduation Cap'],
            ['code' => 'fa-solid fa-school',            'name' => 'School'],
            ['code' => 'fa-solid fa-chalkboard',        'name' => 'Chalkboard'],
            ['code' => 'fa-solid fa-chalkboard-user',   'name' => 'Chalkboard User'],
            ['code' => 'fa-solid fa-book-open-reader',  'name' => 'Book Reader'],
            ['code' => 'fa-solid fa-pencil',            'name' => 'Pencil'],
            ['code' => 'fa-solid fa-ruler',             'name' => 'Ruler'],

            // ---- Weather ----
            ['code' => 'fa-solid fa-sun',               'name' => 'Sun'],
            ['code' => 'fa-solid fa-moon',              'name' => 'Moon'],
            ['code' => 'fa-solid fa-cloud',             'name' => 'Cloud'],
            ['code' => 'fa-solid fa-cloud-rain',        'name' => 'Cloud Rain'],
            ['code' => 'fa-solid fa-cloud-snow',        'name' => 'Cloud Snow'],
            ['code' => 'fa-solid fa-cloud-bolt',        'name' => 'Cloud Bolt'],
            ['code' => 'fa-solid fa-snowflake',         'name' => 'Snowflake'],
            ['code' => 'fa-solid fa-cloud-sun',         'name' => 'Cloud Sun'],

            // ---- Misc & Others ----
            ['code' => 'fa-solid fa-star',              'name' => 'Star'],
            ['code' => 'fa-solid fa-star-half-stroke',  'name' => 'Star Half'],
            ['code' => 'fa-solid fa-heart',             'name' => 'Heart'],
            ['code' => 'fa-solid fa-heart-crack',       'name' => 'Heart Crack'],
            ['code' => 'fa-solid fa-fire',              'name' => 'Fire'],
            ['code' => 'fa-solid fa-fire-flame-curved', 'name' => 'Fire Flame'],
            ['code' => 'fa-solid fa-bolt',              'name' => 'Bolt'],
            ['code' => 'fa-solid fa-bolt-lightning',    'name' => 'Bolt Lightning'],
            ['code' => 'fa-solid fa-diamond',           'name' => 'Diamond'],
            ['code' => 'fa-solid fa-gem',               'name' => 'Gem'],
            ['code' => 'fa-solid fa-crown',             'name' => 'Crown'],
            ['code' => 'fa-solid fa-flag',              'name' => 'Flag'],
            ['code' => 'fa-solid fa-flag-checkered',    'name' => 'Flag Checkered'],
            ['code' => 'fa-solid fa-thumbtack',         'name' => 'Thumbtack'],
            ['code' => 'fa-solid fa-paperclip',         'name' => 'Paperclip'],
            ['code' => 'fa-solid fa-link',              'name' => 'Link'],
            ['code' => 'fa-solid fa-magnet',            'name' => 'Magnet'],
            ['code' => 'fa-solid fa-bullseye',          'name' => 'Bullseye'],
            ['code' => 'fa-solid fa-crosshairs',        'name' => 'Crosshairs'],
            ['code' => 'fa-solid fa-eye-dropper',       'name' => 'Eye Dropper'],
            ['code' => 'fa-solid fa-vial',              'name' => 'Vial'],
            ['code' => 'fa-solid fa-vials',             'name' => 'Vials'],
            ['code' => 'fa-solid fa-flask',             'name' => 'Flask'],
            ['code' => 'fa-solid fa-shield-halved',     'name' => 'Shield Halved'],
            ['code' => 'fa-solid fa-id-badge',          'name' => 'ID Badge'],
            ['code' => 'fa-solid fa-id-card',           'name' => 'ID Card'],
            ['code' => 'fa-solid fa-passport',          'name' => 'Passport'],
            ['code' => 'fa-solid fa-address-card',      'name' => 'Address Card'],
            ['code' => 'fa-solid fa-clipboard',         'name' => 'Clipboard'],
            ['code' => 'fa-solid fa-clipboard-list',    'name' => 'Clipboard List'],
            ['code' => 'fa-solid fa-clipboard-check',   'name' => 'Clipboard Check'],
            ['code' => 'fa-solid fa-notes-sticky',      'name' => 'Sticky Note'],
            ['code' => 'fa-solid fa-calendar-check',    'name' => 'Calendar Check'],
            ['code' => 'fa-solid fa-circle-notch',      'name' => 'Circle Notch'],
            ['code' => 'fa-solid fa-spinner',           'name' => 'Spinner'],
            ['code' => 'fa-solid fa-ban',               'name' => 'Ban'],
            ['code' => 'fa-solid fa-burst',             'name' => 'Burst'],
            ['code' => 'fa-solid fa-compact-disc',      'name' => 'Compact Disc'],
            ['code' => 'fa-solid fa-copyright',         'name' => 'Copyright'],
            ['code' => 'fa-solid fa-database',          'name' => 'Database'],
            ['code' => 'fa-solid fa-expand',            'name' => 'Expand'],
            ['code' => 'fa-solid fa-compress',          'name' => 'Compress'],
            ['code' => 'fa-solid fa-maximize',          'name' => 'Maximize'],
            ['code' => 'fa-solid fa-minimize',          'name' => 'Minimize'],
            ['code' => 'fa-solid fa-random',            'name' => 'Random'],
            ['code' => 'fa-solid fa-sort',              'name' => 'Sort'],
            ['code' => 'fa-solid fa-sort-asc',          'name' => 'Sort Ascending'],
            ['code' => 'fa-solid fa-sort-desc',         'name' => 'Sort Descending'],
            ['code' => 'fa-solid fa-filter',            'name' => 'Filter'],
            ['code' => 'fa-solid fa-window-maximize',   'name' => 'Window Maximize'],
            ['code' => 'fa-solid fa-window-minimize',   'name' => 'Window Minimize'],
            ['code' => 'fa-solid fa-window-restore',    'name' => 'Window Restore'],
            ['code' => 'fa-solid fa-xmark',             'name' => 'Close'],
            ['code' => 'fa-solid fa-minus',             'name' => 'Minimize'],
            ['code' => 'fa-solid fa-square',            'name' => 'Square'],
            ['code' => 'fa-solid fa-circle',            'name' => 'Circle'],
        ];

        foreach ($icons as $icon) {
            Icon::updateOrCreate(
                ['code' => $icon['code'], 'name' => $icon['name']],
                $icon
            );
        }
    }
}
