<section class="pt-12 border-t border-gray-200 px-6 sm:px-10 max-w-7xl mx-auto space-y-24 py-8">

    <div class="max-w-7xl mx-auto space-y-8">

        <!-- HEADER: CATEGORIES & NAVIGATION SLIDER -->
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">

            <!-- Category Tabs -->
            <div class="flex items-center space-x-3 overflow-x-auto no-scrollbar pb-2 sm:pb-0" id="category-tabs">
                <button onclick="changeCategory('spare-parts', this)"
                    class="tab-btn px-6 py-3 rounded-full text-xs font-semibold uppercase tracking-wider transition-all duration-200 bg-black text-white shadow-sm">
                    SPARE PARTS
                </button>
                <button onclick="changeCategory('headphones', this)"
                    class="tab-btn px-6 py-3 rounded-full text-xs font-semibold uppercase tracking-wider transition-all duration-200 bg-gray-100 text-gray-800 hover:bg-gray-200">
                    For HEADPHONES
                </button>
                <button onclick="changeCategory('speakers', this)"
                    class="tab-btn px-6 py-3 rounded-full text-xs font-semibold uppercase tracking-wider transition-all duration-200 bg-gray-100 text-gray-800 hover:bg-gray-200">
                    For SPEAKERS
                </button>
            </div>

            <!-- Slider Control Buttons -->
            <div class="flex items-center space-x-3 self-end sm:self-auto">
                <button id="slideLeft"
                    class="w-10 h-10 rounded-full border border-gray-200 flex items-center justify-center text-gray-600 hover:border-black hover:text-black transition duration-200"
                    aria-label="Slide Left">
                    <i class="fa-solid fa-chevron-left text-xs"></i>
                </button>
                <button id="slideRight"
                    class="w-10 h-10 rounded-full border border-gray-200 flex items-center justify-center text-gray-600 hover:border-black hover:text-black transition duration-200"
                    aria-label="Slide Right">
                    <i class="fa-solid fa-chevron-right text-xs"></i>
                </button>
            </div>

        </div>

        <!-- PRODUCT SLIDER CONTAINER -->
        <div id="product-slider" class="flex space-x-6 overflow-x-auto no-scrollbar scroll-smooth py-4 px-1">
            <!-- Product Cards generated by JavaScript -->
        </div>

    </div>

</section>

<!-- JAVASCRIPT LOGIC -->
<script>
    // Data Produk per Kategori
    const productsData = {
        'spare-parts': [
            {
                id: 1,
                title: "Charging Case for AIR+ 3",
                price: "€69,00",
                status: "Add to Cart",
                image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=500&q=80",
                colors: ["#1e2022", "#f3f4f6", "#c3d5cc"]
            },
            {
                id: 2,
                title: "Charging Case for AIR+ (2nd Gen)",
                price: "€49,00",
                status: "Sold Out",
                image: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?auto=format&fit=crop&w=500&q=80",
                colors: ["#1f2430", "#f4e4e1"]
            },
            {
                id: 3,
                title: "Charging Case for AIR Color",
                price: "€39,00",
                status: "Choose options",
                image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=500&q=80",
                colors: ["#89a4d8", "#ffffff", "#f8c0c8"]
            },
            {
                id: 4,
                title: "Single Earbud for AIR+ 3",
                price: "€69,00",
                status: "Add to Cart",
                image: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=500&q=80",
                colors: ["#121212", "#ffffff", "#b8d8cc"]
            },
            {
                id: 5,
                title: "Silicone Ear Tips Pack (AIR+)",
                price: "€15,00",
                status: "Add to Cart",
                image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=500&q=80",
                colors: ["#ffffff", "#000000"]
            }
        ],
        'headphones': [
            {
                id: 6,
                title: "Track Wireless Headphones",
                price: "€149,00",
                status: "Add to Cart",
                image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=500&q=80",
                colors: ["#000000", "#d1d5db"]
            },
            {
                id: 7,
                title: "Headband Cushion Replacement",
                price: "€25,00",
                status: "Choose options",
                image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=500&q=80",
                colors: ["#1e293b", "#e2e8f0"]
            }
        ],
        'speakers': [
            {
                id: 8,
                title: "Zipp 2 Smart Speaker Battery",
                price: "€59,00",
                status: "Add to Cart",
                image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=500&q=80",
                colors: ["#111827"]
            },
            {
                id: 9,
                title: "Speaker Power Adapter 30W",
                price: "€29,00",
                status: "Add to Cart",
                image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=500&q=80",
                colors: ["#ffffff", "#000000"]
            }
        ]
    };

    // Render Produk ke Slider
    function renderProducts(categoryKey) {
        const slider = document.getElementById('product-slider');
        slider.innerHTML = '';

        const products = productsData[categoryKey] || [];

        products.forEach(product => {
            const card = document.createElement('div');
            card.className = "flex-none w-[270px] sm:w-[300px] bg-[#f9f9f9] rounded-2xl p-6 relative group flex flex-col justify-between transition-all duration-300 hover:shadow-md";

            // Quick View Icon Top Right
            const quickViewBtn = `
                <button class="absolute top-4 right-4 w-9 h-9 rounded-full bg-white flex items-center justify-center text-gray-600 opacity-0 group-hover:opacity-100 transition-opacity duration-200 shadow-sm hover:text-black">
                    <i class="fa-regular fa-eye text-xs"></i>
                </button>
            `;

            // Color Swatches
            const colorSwatches = product.colors.map(color => `
                <span class="w-3.5 h-3.5 rounded-full border border-gray-200 inline-block" style="background-color: ${color}"></span>
            `).join('');

            // Action Button (Sold Out vs Add to Cart)
            const isSoldOut = product.status === "Sold Out";
            const buttonStyle = isSoldOut
                ? "bg-white text-gray-800 border border-gray-300 pointer-events-none"
                : "bg-black text-white hover:bg-gray-800";

            card.innerHTML = `
                ${quickViewBtn}
                
                <!-- Product Image Container -->
                <div class="relative w-full h-48 flex items-center justify-center my-4 overflow-hidden">
                    <img src="${product.image}" alt="${product.title}" class="h-36 object-contain mix-blend-multiply group-hover:scale-105 transition-transform duration-300">
                    
                    <!-- Hover Action Button -->
                    <div class="absolute bottom-0 inset-x-0 flex justify-center opacity-0 group-hover:opacity-100 transform translate-y-2 group-hover:translate-y-0 transition-all duration-300">
                        <button class="px-6 py-2.5 rounded-full text-xs font-semibold shadow-md transition ${buttonStyle}">
                            ${product.status}
                        </button>
                    </div>
                </div>

                <!-- Product Details -->
                <div class="space-y-4 pt-4">
                    <div class="flex justify-between items-start gap-2">
                        <h3 class="text-sm font-semibold text-gray-900 leading-snug">${product.title}</h3>
                        <span class="text-xs font-medium text-gray-700 whitespace-nowrap">${product.price}</span>
                    </div>
                    
                    <!-- Swatches -->
                    <div class="flex items-center space-x-1.5">
                        ${colorSwatches}
                    </div>
                </div>
            `;

            slider.appendChild(card);
        });
    }

    // Kategori Switch Logic
    function changeCategory(categoryKey, btnElement) {
        // Reset kustomisasi tombol
        document.querySelectorAll('.tab-btn').forEach(btn => {
            btn.className = "tab-btn px-6 py-3 rounded-full text-xs font-semibold uppercase tracking-wider transition-all duration-200 bg-gray-100 text-gray-800 hover:bg-gray-200";
        });

        // Set tombol aktif
        btnElement.className = "tab-btn px-6 py-3 rounded-full text-xs font-semibold uppercase tracking-wider transition-all duration-200 bg-black text-white shadow-sm";

        // Render ulang produk
        renderProducts(categoryKey);
    }

    // Slider Navigation Logic
    const slider = document.getElementById('product-slider');
    document.getElementById('slideRight').onclick = () => {
        slider.scrollBy({ left: 320, behavior: 'smooth' });
    };
    document.getElementById('slideLeft').onclick = () => {
        slider.scrollBy({ left: -320, behavior: 'smooth' });
    };

    // Initialize Load
    renderProducts('spare-parts');
</script>